import type { PresetDefinition } from '../types.js';

/**
 * Commu tech / dev / ops : annonces, général, help (salon de support),
 * ressources (partage de liens / docs), showcase (projets perso).
 * Deux rôles : modérateur minimal et contributeur (hoist, mentionnable
 * pour remercier). Pas de voice par défaut (les commus tech y mettent
 * rarement le pied, ça restera au libre choix de l'admin).
 */
export const communityTechSmall: PresetDefinition = {
  id: 'community-tech-small',
  name: 'Commu tech / dev',
  description:
    'Salons annonces, général, aide, ressources et vitrine. Rôle modérateur minimal et rôle contributeur pour celles et ceux qui partagent régulièrement. Slowmode sur #help pour éviter les murs de messages.',
  tags: ['tech', 'dev', 'ops', 'text-only'],
  locale: 'both',
  roles: [
    {
      localId: 'role-mod',
      name: 'Modérateur',
      nameFr: 'Modérateur',
      nameEn: 'Moderator',
      color: 0x3498db,
      permissionPreset: 'moderator-minimal',
      hoist: true,
      mentionable: true,
    },
    {
      localId: 'role-contributor',
      name: 'Contributeur',
      nameFr: 'Contributeur',
      nameEn: 'Contributor',
      color: 0x9b59b6,
      permissionPreset: 'member-default',
      hoist: true,
      mentionable: true,
    },
  ],
  categories: [
    {
      localId: 'cat-info',
      name: 'info',
      nameFr: 'info',
      nameEn: 'info',
      position: 0,
    },
    {
      localId: 'cat-discuss',
      name: 'discussions',
      nameFr: 'discussions',
      nameEn: 'discussions',
      position: 1,
    },
  ],
  channels: [
    {
      localId: 'chan-announcements',
      categoryLocalId: 'cat-info',
      name: 'annonces',
      nameFr: 'annonces',
      nameEn: 'announcements',
      type: 'text',
      topic: 'Annonces du serveur, releases, événements.',
      topicFr: 'Annonces du serveur, releases, événements.',
      topicEn: 'Server announcements, releases, events.',
      slowmodeSeconds: 0,
      readableBy: [],
      writableBy: ['role-mod'],
    },
    {
      localId: 'chan-general',
      categoryLocalId: 'cat-discuss',
      name: 'general',
      nameFr: 'général',
      nameEn: 'general',
      type: 'text',
      topic: 'Discussion générale, hors-sujet tolérés.',
      topicFr: 'Discussion générale, hors-sujet tolérés.',
      topicEn: 'General discussion, off-topic welcome.',
      slowmodeSeconds: 0,
      readableBy: [],
      writableBy: [],
    },
    {
      localId: 'chan-help',
      categoryLocalId: 'cat-discuss',
      name: 'help',
      nameFr: 'aide',
      nameEn: 'help',
      type: 'text',
      topic: 'Questions techniques. Un sujet par message, pensez à marquer résolu.',
      topicFr: 'Questions techniques. Un sujet par message, pensez à marquer résolu.',
      topicEn: 'Technical questions. One topic per message, mark resolved when done.',
      slowmodeSeconds: 15,
      readableBy: [],
      writableBy: [],
    },
    {
      localId: 'chan-resources',
      categoryLocalId: 'cat-info',
      name: 'ressources',
      nameFr: 'ressources',
      nameEn: 'resources',
      type: 'text',
      topic: 'Liens, docs, outils. Pas de discussion, juste du partage.',
      topicFr: 'Liens, docs, outils. Pas de discussion, juste du partage.',
      topicEn: 'Links, docs, tools. No discussion, just sharing.',
      slowmodeSeconds: 60,
      readableBy: [],
      writableBy: ['role-mod', 'role-contributor'],
    },
    {
      localId: 'chan-showcase',
      categoryLocalId: 'cat-discuss',
      name: 'showcase',
      nameFr: 'vitrine',
      nameEn: 'showcase',
      type: 'text',
      topic: 'Vos projets, ce que vous construisez. Un post par projet.',
      topicFr: 'Vos projets, ce que vous construisez. Un post par projet.',
      topicEn: 'Your projects, what you are building. One post per project.',
      slowmodeSeconds: 300,
      readableBy: [],
      writableBy: [],
    },
    {
      localId: 'chan-logs',
      categoryLocalId: 'cat-info',
      name: 'logs',
      nameFr: 'logs',
      nameEn: 'logs',
      type: 'text',
      topic: 'Journal des actions modérateurs et événements serveur.',
      topicFr: 'Journal des actions modérateurs et événements serveur.',
      topicEn: 'Server moderation and event log.',
      slowmodeSeconds: 0,
      readableBy: ['role-mod'],
      writableBy: ['role-mod'],
    },
  ],
  modules: [
    {
      moduleId: 'hello-world',
      enabled: true,
      config: { welcomeDelayMs: 1000 },
    },
    {
      moduleId: 'moderation',
      enabled: false,
      config: {
        version: 1,
        mutedRoleId: null,
        dmOnSanction: true,
        automod: {
          rules: [
            {
              id: 'rule-spam-links',
              label: 'Spam de liens (3+)',
              kind: 'regex',
              pattern: '(https?://[^ ]+\\s+){3,}',
              action: 'delete',
              durationMs: null,
              enabled: true,
            },
            {
              id: 'rule-everyone-abuse',
              label: 'Mention @everyone abusive',
              kind: 'regex',
              pattern: '@(everyone|here)',
              action: 'warn',
              durationMs: null,
              enabled: true,
            },
          ],
          bypassRoleIds: ['@role:role-mod'],
        },
      },
    },
    {
      moduleId: 'welcome',
      enabled: false,
      config: {
        accountAgeFilter: { enabled: true, minDays: 1, action: 'kick', quarantineRoleId: null },
      },
    },
    {
      // Pré-câble le module logs sur le salon `chan-logs` créé par
      // ce preset. Le placeholder `@channel:chan-logs` est résolu
      // par `core.patchModuleConfig` au moment de l'apply.
      moduleId: 'logs',
      enabled: false,
      config: { channelId: '@channel:chan-logs' },
    },
  ],
  permissionBindings: [{ permissionId: 'logs.config.manage', roleLocalId: 'role-mod' }],
};
